export const FIELDS = {
  log: {
    topics: true,
    data: true,
    transactionHash: true,
  },
  transaction: {
    hash: true,
    input: true,
    from: true,
    value: true,
    status: true,
  },
};

export enum NETWORK {
  ETH_SEPOLIA = "eth-sepolia",
  POLYGON_MUMBAI = "polygon-mumbai",
}

export enum CONTRACT {
  RENTAL_MANAGER,
  RENTAL_FACTORY,
}

export const ETH_SEPOLIA_FROM_BLOCK = 3923754;
export const ETH_SEPOLIA_RENTAL_FACTORY_ADDRESS =
  "0x2c2bba22aa19ba34bc5ba65e6c35ce54da36a33d";
export const ETH_SEPOLIA_RENTAL_MANAGER_ADDRESS =
  "0xea0b609f81b3d7699a970e670ec471daf687e5c2";

export const POLYGON_MUMBAI_FROM_BLOCK = 39784442;
export const POLYGON_MUMBAI_RENTAL_FACTORY_ADDRESS =
  "0x936A9E959ad3f8d79134b61051123c32CEe62F25";
export const POLYGON_MUMBAI_RENTAL_MANAGER_ADDRESS =
  "0xB5A0aB4B81B2621ef166E9f6E941A00b44c619b2";

export const CONTRACT_ADDRESS = {
  [NETWORK.ETH_SEPOLIA]: {
    [CONTRACT.RENTAL_MANAGER]: ETH_SEPOLIA_RENTAL_MANAGER_ADDRESS,
    [CONTRACT.RENTAL_FACTORY]: ETH_SEPOLIA_RENTAL_FACTORY_ADDRESS,
  },
  [NETWORK.POLYGON_MUMBAI]: {
    [CONTRACT.RENTAL_MANAGER]: POLYGON_MUMBAI_RENTAL_MANAGER_ADDRESS,
    [CONTRACT.RENTAL_FACTORY]: POLYGON_MUMBAI_RENTAL_FACTORY_ADDRESS,
  },
};
